server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
